---
- name: Create the cache.example.com/v1alpha1.Configmap
  k8s:
    state: present
    namespace: '{{ namespace }}'
    definition: "{{ lookup('template', '/'.join([samples_dir, cr_file])) | from_yaml }}"
    wait: yes
    wait_timeout: 300
    wait_condition:
      type: Successful
      status: "True"
  vars:
    cr_file: 'cache_v1alpha1_configmap.yaml'

- debug: var=configmap
  vars:
    configmap: '{{lookup("kubernetes.core.k8s", api_version="v1", kind="ConfigMap", namespace="default", resource_name="my-configmap") }}'

- debug: var=namesp
  vars:
    namesp: '{{lookup("kubernetes.core.k8s", api_version="v1", kind="Namespace") }}'

- assert: 
    that: configmap.data.key == 'Hello world'
  vars:
    configmap: '{{lookup("kubernetes.core.k8s", api_version="v1", kind="ConfigMap", namespace="default", resource_name="my-configmap") }}'
