---
- name: ConfigMap Example is "{{ state }}"
  kubernetes.core.k8s:
    definition: 
      kind: ConfigMap
      apiVersion: v1
      metadata: 
        name: my-configmap
        namespace: default
      data:
        key: "Hello world"  
    state: "{{ state }}"
  ignore_errors: true