# permissions for end users to view webapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: webapp-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: helm-operator
    app.kubernetes.io/part-of: helm-operator
    app.kubernetes.io/managed-by: kustomize
  name: webapp-viewer-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - webapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - webapps/status
  verbs:
  - get
