# permissions for end users to view ansibledevs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ansibledev-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ansibledev-operator
    app.kubernetes.io/part-of: ansibledev-operator
    app.kubernetes.io/managed-by: kustomize
  name: ansibledev-viewer-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - ansibledevs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - ansibledevs/status
  verbs:
  - get
