- name: Create a Service object from an inline definition
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: web
        namespace: devlopment
        labels:
          app: helloworld
      spec:
        selector:
          app: helloworld
        ports:
        - protocol: TCP
          targetPort: node-port
          port: 8000
        type: NodePort